tag: 2.15.1
host: default.minikube.local
---
# Global settings
# create defectdojo specific secret
createSecret: true
# create rabbitmq secret in defectdojo chart, outside of rabbitmq chart
createRabbitMqSecret: true
# create redis secret in defectdojo chart, outside of redis chart
createRedisSecret: true
# create mysql secret in defectdojo chart, outside of mysql chart
createMysqlSecret: true
# create postgresql secret in defectdojo chart, outside of postgresql chart
createPostgresqlSecret: true
# create postgresql-ha secret in defectdojo chart, outside of postgresql-ha chart
createPostgresqlHaSecret: false
# create postgresql-ha-pgpool secret in defectdojo chart, outside of postgresql-ha chart
createPostgresqlHaPgpoolSecret: false

# Network settings
django:
  ingress:
    enabled: true
    activateTLS: false
