apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cluster
  namespace: default
spec:
  interval: 1m0s
  url: ssh://git@github.com/mlunato47/flux-example.git
  ref:
    branch: main
  secretRef:
    name: gh-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: defectdojo
  namespace: default
spec:
  interval: 1m0s
  path: "./flux-example/clusters/my-cluster/defectdojo"
  sourceRef:
    kind: GitRepository
    name: cluster
    namespace: default