apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: defectdojo

commonLabels:
  owner: VIT

resources:
  - defectdojo-gitrepository.yaml
  - defectdojo-helmrelease.yaml

configurations:
  - kustomizeconfig.yaml

configMapGenerator:
  - name: defectdojo-base-values
    files:
      - values.yaml=defectdojo-base-values.yaml

# helmCharts:
# - name: defectdojo
#   repo: https://github.com/DefectDojo/django-DefectDojo/helm/defectdojo/Chart.yaml
#   namespace: defectdojo
#   #configHome: ./helm/defectdojo

# helmChartInflationGenerator:
#   - chartName: defectdojo
#     chartRepoUrl: https://github.com/DefectDojo/django-DefectDojo.git//helm/defectdojo
#     releaseName: defectdojo
#     releaseNamespace: defectdojo
#     chartHome: ./helm/defectdojo
#     # override with these custom values
#     values: values.yaml